# Generated by Django 6.1.1 on 2026-09-16 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='VD: admin, manager, receptionist, housekeeping', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Ca sáng, Ca chiều, Ca đêm', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'db_table': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Đường dẫn ảnh đại diện nhân viên (lưu trên storage/CDN, không lưu binary trong DB)', max_length=500, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_branch', models.ForeignKey(help_text='Chi nhánh chính (biên chế)', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='branches.branch')),
                ('user', models.OneToOneField(blank=True, help_text='Tài khoản đăng nhập hệ thống (Django User)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.role')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBranch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_from', models.DateField()),
                ('assigned_to', models.DateField(blank=True, help_text='NULL = vẫn đang làm việc tại chi nhánh này', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='branches.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Điều động nhân viên',
                'verbose_name_plural': 'Điều động nhân viên',
                'db_table': 'employee_branches',
                'constraints': [models.UniqueConstraint(fields=('employee', 'branch', 'assigned_from'), name='uq_empbranch')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('checked_in', 'Đã chấm công'), ('absent', 'Vắng'), ('leave', 'Nghỉ phép')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='branches.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='staff.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='staff.shift')),
            ],
            options={
                'verbose_name': 'Lịch phân ca',
                'verbose_name_plural': 'Lịch phân ca',
                'db_table': 'employee_shift_schedule',
                'indexes': [models.Index(fields=['work_date', 'branch'], name='idx_schedule_date')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'shift'), name='uq_schedule')],
            },
        ),
    ]
