# Generated by Django 6.1.1 on 2026-09-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='home_branch',
            field=models.ForeignKey(blank=True, help_text='Chi nhánh chính (biên chế)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.role'),
        ),
    ]
