# Generated by Django 6.1.1 on 2026-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('id_card_type', models.CharField(blank=True, choices=[('cccd', 'CCCD'), ('cmnd', 'CMND'), ('passport', 'Passport'), ('other', 'Khác')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'customers',
                'indexes': [models.Index(fields=['full_name'], name='idx_customers_name')],
            },
        ),
    ]
