# Generated by Django 6.1.1 on 2026-09-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Standard, Deluxe, Suite', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2)),
                ('bed_type', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loại phòng',
                'verbose_name_plural': 'Loại phòng',
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Cao điểm Tết 2027, Thấp điểm hè', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Ưu tiên khi trùng khoảng ngày, số lớn hơn = ưu tiên hơn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mùa giá',
                'verbose_name_plural': 'Mùa giá',
                'db_table': 'seasons',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='idx_seasons_dates')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='chk_seasons_dates')],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='Đường dẫn ảnh trên storage/CDN, không lưu binary', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Ảnh đại diện/thumbnail chính')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL = ảnh minh họa chung; điền cụ thể nếu ảnh chụp riêng tại 1 chi nhánh', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='branches.branch')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Ảnh loại phòng',
                'verbose_name_plural': 'Ảnh loại phòng',
                'db_table': 'room_images',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['room_type', 'sort_order'], name='idx_roomimages_type')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(help_text='VD: 101, 305', max_length=20)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đang có khách'), ('cleaning', 'Đang dọn dẹp'), ('maintenance', 'Bảo trì'), ('blocked', 'Khóa phòng')], default='available', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='branches.branch')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'db_table': 'rooms',
                'indexes': [models.Index(fields=['status'], name='idx_rooms_status'), models.Index(fields=['branch', 'room_type'], name='idx_rooms_branch_type')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'room_number'), name='uq_rooms_branch_number')],
            },
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate_type', models.CharField(choices=[('hourly', 'Theo giờ'), ('daily', 'Theo ngày'), ('monthly', 'Theo tháng')], default='daily', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('first_hours', models.PositiveSmallIntegerField(blank=True, help_text='Số giờ đầu tính trong đơn giá (chỉ dùng khi rate_type=hourly)', null=True)),
                ('extra_hour_price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá mỗi giờ phát sinh thêm (chỉ dùng khi rate_type=hourly)', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_prices', to='branches.branch')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='rooms.roomtype')),
                ('season', models.ForeignKey(blank=True, help_text='NULL = giá mặc định (áp dụng khi không rơi vào mùa nào)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_prices', to='rooms.season')),
            ],
            options={
                'verbose_name': 'Bảng giá phòng',
                'verbose_name_plural': 'Bảng giá phòng',
                'db_table': 'room_prices',
                'constraints': [models.UniqueConstraint(fields=('branch', 'room_type', 'season', 'rate_type'), name='uq_prices_combo')],
            },
        ),
    ]
