# Generated by Django 6.1.1 on 2026-09-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_code', models.CharField(max_length=30, unique=True)),
                ('subtotal_rooms', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền phòng', max_digits=14)),
                ('subtotal_services', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền dịch vụ', max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tổng phải thu = subtotal_rooms + subtotal_services - discount + tax', max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tổng đã thu, cập nhật từ bảng payments', max_digits=14)),
                ('status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('partial', 'Thanh toán một phần'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='unpaid', max_length=15)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('credit_card', 'Thẻ tín dụng'), ('e_wallet', 'Ví điện tử'), ('other', 'Khác')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_type', models.CharField(choices=[('deposit', 'Đặt cọc'), ('partial', 'Thanh toán một phần'), ('full', 'Thanh toán đủ'), ('refund', 'Hoàn tiền')], default='partial', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(blank=True, help_text='Mã giao dịch/chuyển khoản nếu có', max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('received_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoices_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='idx_payments_invoice'),
        ),
    ]
