# Generated by Django 6.1.1 on 2026-09-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Trực tiếp, Booking.com, Agoda, Traveloka', max_length=100)),
                ('source_type', models.CharField(choices=[('direct', 'Trực tiếp'), ('ota', 'OTA'), ('phone', 'Điện thoại'), ('walk_in', 'Khách vãng lai'), ('other', 'Khác')], default='direct', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Phần trăm hoa hồng OTA, VD: 15.00', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nguồn đặt phòng',
                'verbose_name_plural': 'Nguồn đặt phòng',
                'db_table': 'booking_sources',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_code', models.CharField(help_text='VD: BK20260823001', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('checked_in', 'Đã check-in'), ('checked_out', 'Đã check-out'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='pending', max_length=15)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='branches.branch')),
                ('created_by_employee', models.ForeignKey(blank=True, help_text='Nhân viên tạo đơn (NULL nếu khách tự đặt online)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to='staff.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('booking_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.bookingsource')),
            ],
            options={
                'verbose_name': 'Đơn đặt phòng',
                'verbose_name_plural': 'Đơn đặt phòng',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate_type', models.CharField(choices=[('hourly', 'Theo giờ'), ('daily', 'Theo ngày'), ('monthly', 'Theo tháng')], default='daily', max_length=10)),
                ('check_in_planned', models.DateTimeField()),
                ('check_out_planned', models.DateTimeField()),
                ('check_in_actual', models.DateTimeField(blank=True, null=True)),
                ('check_out_actual', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot giá tại thời điểm đặt (không tham chiếu động vào room_prices)', max_digits=12)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('booked', 'Đã đặt'), ('checked_in', 'Đã check-in'), ('checked_out', 'Đã check-out'), ('cancelled', 'Đã hủy')], default='booked', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_details', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Chi tiết đặt phòng',
                'verbose_name_plural': 'Chi tiết đặt phòng',
                'db_table': 'booking_details',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='VD: Ăn sáng, Giặt ủi, Đưa đón sân bay', max_length=100)),
                ('unit', models.CharField(default='lần', help_text='VD: lần, suất, kg', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL = dịch vụ áp dụng chung toàn chuỗi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot giá dịch vụ tại thời điểm sử dụng', max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_used', to='bookings.bookingdetail')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_services', to='bookings.service')),
            ],
            options={
                'verbose_name': 'Dịch vụ đã sử dụng',
                'verbose_name_plural': 'Dịch vụ đã sử dụng',
                'db_table': 'booking_services',
            },
        ),
        migrations.AddIndex(
            model_name='bookingdetail',
            index=models.Index(fields=['room', 'check_in_planned', 'check_out_planned'], name='idx_details_room_dates'),
        ),
        migrations.AddIndex(
            model_name='bookingdetail',
            index=models.Index(fields=['booking'], name='idx_details_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingdetail',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_planned__gt', models.F('check_in_planned'))), name='chk_details_dates'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_bookings_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['branch', 'status'], name='idx_bookings_branch'),
        ),
    ]
